# Generated by Django 3.0.3 on 2020-02-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mittapp', '0002_auto_20200209_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='date',
            field=models.IntegerField(),
        ),
    ]
